platform :ios, '17.0'
use_frameworks!

target 'SquatCounter' do
  pod 'MediaPipeTasksVision'
  target 'SquatCounterInferenceTests' do
    inherit! :search_paths
  end
end

target 'SquatCounterCoreTests' do
  inherit! :search_paths
end
