import React from 'react';
import {AbsoluteFill, Img, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {Video} from '@remotion/media';
import '@fontsource/barlow-condensed/700.css';
import '@fontsource-variable/atkinson-hyperlegible-next/index.css';

const ink = '#0B0D10';
const paper = '#F7F7F5';
const blue = '#2F5BFF';
const orange = '#FF5C35';
const muted = '#CDD1DA';
const display = 'Barlow Condensed';
const body = 'Atkinson Hyperlegible Next Variable';

const Pane = ({children, left, top, width, height}: React.PropsWithChildren<{
  left: number;
  top: number;
  width: number;
  height: number;
}>) => (
  <div style={{position: 'absolute', left, top, width, height, overflow: 'hidden', border: `2px solid ${paper}44`}}>
    {children}
  </div>
);

const Tag = ({text, left, top, color = blue}: {text: string; left: number; top: number; color?: string}) => (
  <div style={{position: 'absolute', left, top, backgroundColor: color, color: paper,
    padding: '11px 20px', fontFamily: body, fontSize: 31, fontWeight: 700, lineHeight: 1}}>
    {text}
  </div>
);

// The iPhone capture shows the app replaying the previously analysed Pexels file.
// Its replay begins around 20.8 s in the screen recording. These trims select
// real frames; no pose or counter graphics are generated by this composition.
const phoneReplayStart = 624;
const sourceReplayStart = 24;

const SceneHook = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <div style={{position: 'absolute', left: 65, top: 43, fontFamily: display,
      fontSize: 108, fontWeight: 700, lineHeight: 0.92}}>QUANDO ENTRA O +1?</div>
    <div style={{position: 'absolute', right: 65, top: 72, fontFamily: body,
      fontSize: 31, color: muted}}>AGACHAMENTO · TESTE NO IPHONE 15</div>
    <Pane left={350} top={182} width={1220} height={655}>
      <Video src={staticFile('phone-full.mov')} trimBefore={735} muted objectFit="cover"
        style={{width: '100%', height: '100%', objectPosition: 'center 18%'}} />
    </Pane>
    <Tag text="CAPTURA REAL DA TELA · RECORTE" left={370} top={199} />
    <div style={{position: 'absolute', left: 65, bottom: 67, fontFamily: body,
      fontSize: 34, color: paper}}>Arquivo licenciado importado e analisado no aparelho antes desta reprodução.</div>
  </AbsoluteFill>
);

const SceneEvidence = () => {
  const frame = useCurrentFrame();
  const headline = frame < 300 ? 'O IPHONE CONTOU?' : 'SÓ VALE NA VOLTA.';
  return (
    <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
      <div style={{position: 'absolute', left: 65, top: 37, fontFamily: display,
        fontSize: 98, fontWeight: 700, lineHeight: 0.95, letterSpacing: '-0.025em'}}>
        {headline}
      </div>
      <div style={{position: 'absolute', right: 65, top: 64, fontFamily: body, fontSize: 31,
        fontWeight: 700, color: muted}}>MVP NO IPHONE 15 · TESTE CONTROLADO</div>

      <Pane left={65} top={185} width={870} height={505}>
        <Video src={staticFile('source.mp4')} trimBefore={sourceReplayStart} muted objectFit="cover"
          style={{width: '100%', height: '100%'}} />
      </Pane>
      <Pane left={985} top={185} width={870} height={505}>
        <Video src={staticFile('phone-full.mov')} trimBefore={phoneReplayStart} muted objectFit="cover"
          style={{width: '100%', height: '100%', objectPosition: 'center 18%'}} />
      </Pane>
      <Tag text="VÍDEO-FONTE" left={84} top={199} color={ink} />
      <Tag text="TELA REAL DO IPHONE · RECORTE" left={1004} top={199} />
      <div style={{position: 'absolute', left: 65, top: 730, width: 1788, height: 2, backgroundColor: `${paper}55`}} />
      <div style={{position: 'absolute', left: 65, top: 774, fontFamily: body, fontSize: 45,
        fontWeight: 650, color: paper}}>
        {frame < 300 ? 'Vídeo importado: análise no iPhone antes da reprodução.' :
          frame < 610 ? 'O contador espera: em pé → descida → fundo → em pé.' :
          'A contagem é local no aparelho. Não avalia técnica ou segurança.'}
      </div>
      <div style={{position: 'absolute', left: 65, bottom: 65, fontFamily: body, fontSize: 28,
        color: muted}}>Imagem: MART PRODUCTION / Pexels · Análise: MediaPipe Pose Landmarker Full</div>
      <div style={{position: 'absolute', right: 65, bottom: 65, fontFamily: body, fontSize: 28,
        color: orange, fontWeight: 700}}>EXPERIMENTO INICIAL</div>
    </AbsoluteFill>
  );
};

const SceneReplay = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <div style={{position: 'absolute', left: 65, top: 47, fontFamily: display, fontSize: 92,
      fontWeight: 700, lineHeight: 1}}>REPLAY: QUANDO A REPETIÇÃO ENTRA?</div>
    <Pane left={65} top={187} width={1120} height={645}>
      <Video src={staticFile('phone-full.mov')} trimBefore={735} muted objectFit="cover"
        style={{width: '100%', height: '100%', objectPosition: 'center 18%'}} />
    </Pane>
    <div style={{position: 'absolute', left: 1240, top: 228, width: 560,
      fontFamily: body, fontSize: 51, lineHeight: 1.18, fontWeight: 650}}>
      Pose estimada<br />
      <span style={{color: '#91A6FF'}}>↓</span> descida<br />
      <span style={{color: '#91A6FF'}}>↓</span> fundo<br />
      <span style={{color: '#91A6FF'}}>↑</span> retorno<br />
      <span style={{color: orange}}>+1 só no fim</span>
    </div>
    <div style={{position: 'absolute', left: 65, bottom: 66, fontFamily: body, fontSize: 31,
      color: muted}}>Arquivo analisado no iPhone antes da reprodução · replay da regra</div>
    <div style={{position: 'absolute', right: 65, bottom: 66, fontFamily: body, fontSize: 29,
      color: orange, fontWeight: 700}}>EXPERIMENTO INICIAL</div>
  </AbsoluteFill>
);

const SceneVerdict = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <Img src={staticFile('source-frame.png')} style={{position: 'absolute', left: 0, top: 0,
      width: 960, height: 1080, objectFit: 'cover', opacity: 0.55}} />
    <div style={{position: 'absolute', left: 0, top: 0, width: 1010, height: 1080,
      background: `linear-gradient(90deg, transparent 50%, ${ink} 100%)`}} />
    <div style={{position: 'absolute', left: 95, top: 90, fontFamily: display, fontSize: 104,
      fontWeight: 700, lineHeight: 0.96}}>UM CLIPE.<br />QUATRO CICLOS.</div>
    <div style={{position: 'absolute', left: 1050, top: 85, width: 770}}>
      <div style={{fontFamily: body, fontSize: 38, color: muted}}>CONFERÊNCIA NESTE VÍDEO</div>
      <div style={{display: 'flex', gap: 80, marginTop: 38}}>
        <div><div style={{fontFamily: display, fontSize: 150, lineHeight: 0.9}}>4</div>
          <div style={{fontFamily: body, fontSize: 36}}>contagem visual</div></div>
        <div><div style={{fontFamily: display, fontSize: 150, lineHeight: 0.9, color: '#91A6FF'}}>4</div>
          <div style={{fontFamily: body, fontSize: 36}}>app no iPhone</div></div>
      </div>
      <div style={{height: 2, backgroundColor: `${paper}55`, marginTop: 65, marginBottom: 45}} />
      <div style={{fontFamily: body, fontSize: 39, lineHeight: 1.25}}>
        <span style={{color: orange, fontWeight: 700}}>Ainda não validado:</span><br />
        faltam 50 repetições anotadas,<br />
        outros ângulos e 10 min de câmera.
      </div>
    </div>
    <div style={{position: 'absolute', left: 95, bottom: 68, fontFamily: body, fontSize: 30,
      color: paper}}>Fonte: MART PRODUCTION / Pexels 8837118</div>
    <div style={{position: 'absolute', right: 95, bottom: 68, fontFamily: body, fontSize: 30,
      color: orange, fontWeight: 700}}>EXPERIMENTO INICIAL</div>
  </AbsoluteFill>
);

export const SquatCounterFinal = () => (
  <AbsoluteFill style={{backgroundColor: ink}}>
    <Sequence from={0} durationInFrames={180} name="Gancho: repetição real"><SceneHook /></Sequence>
    <Sequence from={180} durationInFrames={870} name="Fonte e captura sincronizadas"><SceneEvidence /></Sequence>
    <Sequence from={1050} durationInFrames={270} name="Replay da regra"><SceneReplay /></Sequence>
    <Sequence from={1320} durationInFrames={180} name="Resultado e limites"><SceneVerdict /></Sequence>
  </AbsoluteFill>
);

export const SquatCounterCover = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <Img src={staticFile('source-frame-complete.png')} style={{position: 'absolute', left: 0, top: 240,
      width: 1000, height: 600, objectFit: 'cover'}} />
    <Img src={staticFile('phone-frame-complete.png')} style={{position: 'absolute', left: 1010, top: 240,
      width: 845, height: 600, objectFit: 'cover', objectPosition: 'center 18%'}} />
    <div style={{position: 'absolute', left: 65, top: 38, fontFamily: display, fontWeight: 700,
      fontSize: 138, lineHeight: 0.9}}>O IPHONE CONTOU?</div>
    <div style={{position: 'absolute', right: 65, top: 80, fontFamily: body, fontSize: 39,
      color: muted}}>VISÃO COMPUTACIONAL · MVP REAL</div>
    <Tag text="ORIGINAL" left={85} top={260} color={ink} />
    <Tag text="NO IPHONE 15" left={1030} top={260} />
    <div style={{position: 'absolute', left: 65, bottom: 67, fontFamily: body, fontSize: 40,
      color: paper}}>4 ciclos no clipe · 4 no app</div>
    <div style={{position: 'absolute', right: 65, bottom: 67, fontFamily: body,
      fontSize: 30, color: orange, fontWeight: 700}}>EXPERIMENTO INICIAL</div>
  </AbsoluteFill>
);
