import React from 'react';
import {AbsoluteFill, Img, Sequence, staticFile, useCurrentFrame} from 'remotion';
import {Video} from '@remotion/media';
import '@fontsource/barlow-condensed/700.css';
import '@fontsource-variable/atkinson-hyperlegible-next/index.css';

const ink = '#0B0D10';
const paper = '#F7F7F5';
const blue = '#2F5BFF';
const orange = '#FF5C35';
const muted = '#CDD1DA';
const display = 'Barlow Condensed';
const body = 'Atkinson Hyperlegible Next Variable';

const Pane = ({children, left, top, width, height}: React.PropsWithChildren<{
  left: number;
  top: number;
  width: number;
  height: number;
}>) => (
  <div style={{position: 'absolute', left, top, width, height, overflow: 'hidden', border: `2px solid ${paper}44`}}>
    {children}
  </div>
);

const Tag = ({text, left, top, color = blue}: {text: string; left: number; top: number; color?: string}) => (
  <div style={{position: 'absolute', left, top, backgroundColor: color, color: paper,
    padding: '11px 20px', fontFamily: body, fontSize: 31, fontWeight: 700, lineHeight: 1}}>
    {text}
  </div>
);

// The iPhone capture shows the app replaying the previously analysed Pexels file.
// Its replay begins around 20.8 s in the screen recording. These trims select
// real frames; no pose or counter graphics are generated by this composition.
const phoneReplayStart = 624;
const sourceReplayStart = 0;

// Landscape edition: the whole, unaltered portrait screen stays visible at left.
// This is the recording from the physical iPhone 15, not the Xcode simulator.
const LandscapePhone = ({trimBefore, still = false}: {trimBefore?: number; still?: boolean}) => (
  <div style={{position: 'absolute', left: 65, top: 92, width: 436, height: 936,
    borderRadius: 55, backgroundColor: '#1E222B', border: `3px solid ${paper}77`,
    boxShadow: '0 16px 48px #0008', overflow: 'hidden'}}>
    <div style={{position: 'absolute', left: 11, top: 11, width: 408, height: 906,
      borderRadius: 44, overflow: 'hidden', backgroundColor: '#000'}}>
      {still ? <Img src={staticFile('phone-frame-complete.png')}
        style={{width: '100%', height: '100%', objectFit: 'contain'}} /> :
        <Video src={staticFile('phone-full.mov')} trimBefore={trimBefore ?? phoneReplayStart}
          muted objectFit="contain" style={{width: '100%', height: '100%'}} />}
    </div>
  </div>
);

const LandscapeSource = ({trimBefore = 0}: {trimBefore?: number}) => (
  <>
    <div style={{position: 'absolute', left: 568, top: 162, fontFamily: body,
      fontSize: 26, fontWeight: 700, color: orange}}>
      TRECHOS EM MOMENTOS DIFERENTES · NÃO SINCRONIZADOS
    </div>
    <Pane left={568} top={211} width={1287} height={682}>
      <Video src={staticFile('source.mp4')} trimBefore={trimBefore} muted objectFit="contain"
        style={{width: '100%', height: '100%', backgroundColor: '#000'}} />
    </Pane>
  </>
);

const LandscapeLabels = () => <>
  <Tag text="TELA REAL · IPHONE 15" left={84} top={21} />
  <Tag text="VÍDEO LICENCIADO" left={588} top={228} color={ink} />
</>;

const SceneHook = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <LandscapePhone trimBefore={735} />
    <LandscapeSource trimBefore={0} />
    <LandscapeLabels />
    <div style={{position: 'absolute', left: 568, top: 42, fontFamily: display,
      fontSize: 101, fontWeight: 700, lineHeight: 0.92}}>QUANDO ENTRA O +1?</div>
    <div style={{position: 'absolute', left: 568, bottom: 70, fontFamily: body,
      fontSize: 29, color: paper}}>Vídeo importado e analisado no iPhone antes desta reprodução.</div>
  </AbsoluteFill>
);

const SceneEvidence = () => {
  const frame = useCurrentFrame();
  const headline = frame < 300 ? 'O IPHONE CONTOU?' : 'SÓ VALE NA VOLTA.';
  return (
    <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
      <LandscapePhone trimBefore={phoneReplayStart} />
      <LandscapeSource trimBefore={sourceReplayStart} />
      <LandscapeLabels />
      <div style={{position: 'absolute', left: 568, top: 36, fontFamily: display,
        fontSize: 94, fontWeight: 700, lineHeight: 0.95, letterSpacing: '-0.025em'}}>
        {headline}
      </div>
      <div style={{position: 'absolute', left: 568, top: 924, width: 1287, height: 2, backgroundColor: `${paper}55`}} />
      <div style={{position: 'absolute', left: 568, top: 951, width: 1287, fontFamily: body, fontSize: 35,
        fontWeight: 650, color: paper}}>
        {frame < 300 ? 'Vídeo importado: análise no iPhone antes da reprodução.' :
          frame < 610 ? 'O contador espera: em pé → descida → fundo → em pé.' :
          'A contagem é local no aparelho. Não avalia técnica ou segurança.'}
      </div>
      <div style={{position: 'absolute', left: 568, bottom: 20, fontFamily: body, fontSize: 22,
        color: muted}}>MART PRODUCTION / Pexels · MediaPipe Pose Landmarker Full · Experimento inicial</div>
    </AbsoluteFill>
  );
};

const SceneReplay = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <LandscapePhone trimBefore={735} />
    <LandscapeSource trimBefore={0} />
    <LandscapeLabels />
    <div style={{position: 'absolute', left: 568, top: 47, fontFamily: display, fontSize: 75,
      fontWeight: 700, lineHeight: 1}}>REPLAY: QUANDO A REPETIÇÃO ENTRA?</div>
    <div style={{position: 'absolute', left: 568, top: 940, fontFamily: body, fontSize: 35,
      color: paper}}>Em pé → descida → fundo → retorno: <span style={{color: orange}}>+1 só no fim.</span></div>
    <div style={{position: 'absolute', left: 568, bottom: 20, fontFamily: body, fontSize: 22,
      color: muted}}>Replay da mesma captura real · sem pose gerada na edição</div>
  </AbsoluteFill>
);

const SceneFourthCount = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <LandscapePhone trimBefore={1470} />
    <LandscapeSource trimBefore={0} />
    <LandscapeLabels />
    <div style={{position: 'absolute', left: 568, top: 45, fontFamily: display,
      fontSize: 95, fontWeight: 700}}>A QUARTA ENTRA AQUI.</div>
    <div style={{position: 'absolute', left: 568, top: 940, fontFamily: body,
      fontSize: 35, color: paper}}>Contagem real da tela do iPhone 15 · resultado limitado a este clipe.</div>
  </AbsoluteFill>
);

const SceneVerdict = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <LandscapePhone still />
    <Tag text="TELA REAL · IPHONE 15" left={84} top={21} />
    <div style={{position: 'absolute', left: 568, top: 73, fontFamily: display, fontSize: 100,
      fontWeight: 700, lineHeight: 0.96}}>UM CLIPE.<br />QUATRO CICLOS.</div>
    <div style={{position: 'absolute', left: 568, top: 375, width: 1260}}>
      <div style={{fontFamily: body, fontSize: 38, color: muted}}>CONFERÊNCIA NESTE CLIPE</div>
      <div style={{display: 'flex', gap: 100, marginTop: 42}}>
        <div><div style={{fontFamily: display, fontSize: 160, lineHeight: 0.9}}>4</div>
          <div style={{fontFamily: body, fontSize: 36}}>contagem visual</div></div>
        <div><div style={{fontFamily: display, fontSize: 160, lineHeight: 0.9, color: '#91A6FF'}}>4</div>
          <div style={{fontFamily: body, fontSize: 36}}>app no iPhone</div></div>
      </div>
      <div style={{height: 2, backgroundColor: `${paper}55`, marginTop: 48, marginBottom: 36}} />
      <div style={{fontFamily: body, fontSize: 36, lineHeight: 1.25}}>
        <span style={{color: orange, fontWeight: 700}}>Ainda não validado:</span><br />
        faltam 50 repetições anotadas,<br />
        outros ângulos e 10 min de câmera.
      </div>
    </div>
    <div style={{position: 'absolute', left: 568, bottom: 60, fontFamily: body, fontSize: 27,
      color: paper}}>Fonte: MART PRODUCTION / Pexels 8837118</div>
    <div style={{position: 'absolute', right: 65, bottom: 60, fontFamily: body, fontSize: 27,
      color: orange, fontWeight: 700}}>EXPERIMENTO INICIAL</div>
  </AbsoluteFill>
);

export const SquatCounterFinal = () => (
  <AbsoluteFill style={{backgroundColor: ink}}>
    <Sequence from={0} durationInFrames={180} name="Gancho: repetição real"><SceneHook /></Sequence>
    <Sequence from={180} durationInFrames={870} name="Comparação entre fonte e captura"><SceneEvidence /></Sequence>
    <Sequence from={1050} durationInFrames={120} name="Quarta contagem real"><SceneFourthCount /></Sequence>
    <Sequence from={1170} durationInFrames={150} name="Replay da regra"><SceneReplay /></Sequence>
    <Sequence from={1320} durationInFrames={180} name="Resultado e limites"><SceneVerdict /></Sequence>
  </AbsoluteFill>
);

export const SquatCounterCover = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <LandscapePhone still />
    <Tag text="TELA REAL · IPHONE 15" left={84} top={21} />
    <Img src={staticFile('source-frame-complete.png')} style={{position: 'absolute', left: 568, top: 215,
      width: 1287, height: 682, objectFit: 'contain', backgroundColor: '#000'}} />
    <Tag text="VÍDEO LICENCIADO" left={588} top={232} color={ink} />
    <div style={{position: 'absolute', left: 568, top: 42, fontFamily: display, fontWeight: 700,
      fontSize: 114, lineHeight: 0.9}}>O IPHONE CONTOU?</div>
    <div style={{position: 'absolute', left: 568, bottom: 82, fontFamily: body, fontSize: 40,
      color: paper}}>4 ciclos no clipe · 4 no app</div>
    <div style={{position: 'absolute', right: 65, bottom: 28, fontFamily: body,
      fontSize: 27, color: orange, fontWeight: 700}}>EXPERIMENTO INICIAL</div>
  </AbsoluteFill>
);

// Feed-first 4:5 variant. It uses the same unmodified source and iPhone capture
// as the landscape edition, but keeps the counter readable on narrow screens.
const SocialHeader = ({title}: {title: string}) => (
  <div style={{position: 'absolute', left: 48, top: 42, right: 48,
    fontFamily: display, fontSize: 88, fontWeight: 700, lineHeight: 0.93,
    color: paper}}>{title}</div>
);

const SocialFooter = ({text}: {text: string}) => (
  <div style={{position: 'absolute', left: 50, right: 50, bottom: 55,
    fontFamily: body, fontSize: 29, color: muted, lineHeight: 1.12}}>{text}</div>
);

const SocialHook = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <SocialHeader title="QUANDO ENTRA O +1?" />
    <Pane left={50} top={228} width={980} height={575}>
      <Video src={staticFile('phone-full.mov')} trimBefore={735} muted objectFit="cover"
        style={{width: '100%', height: '100%', objectPosition: 'center 21%'}} />
    </Pane>
    <Tag text="TELA REAL DO IPHONE 15 · RECORTE" left={65} top={246} />
    <div style={{position: 'absolute', left: 50, top: 885, right: 50,
      fontFamily: body, fontSize: 55, fontWeight: 700, lineHeight: 1.15}}>
      Só conta quando volta a ficar em pé.
    </div>
    <SocialFooter text="Vídeo licenciado importado e analisado no aparelho antes da reprodução." />
  </AbsoluteFill>
);

const SocialEvidence = () => {
  const frame = useCurrentFrame();
  return (
    <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
      <SocialHeader title={frame < 390 ? 'O IPHONE CONTOU?' : 'SÓ VALE NA VOLTA.'} />
      <Pane left={50} top={200} width={980} height={440}>
        <Video src={staticFile('source.mp4')} trimBefore={sourceReplayStart} muted objectFit="cover"
          style={{width: '100%', height: '100%'}} />
      </Pane>
      <Tag text="VÍDEO-FONTE" left={65} top={214} color={ink} />
      <Pane left={50} top={667} width={980} height={440}>
        <Video src={staticFile('phone-full.mov')} trimBefore={phoneReplayStart} muted objectFit="cover"
          style={{width: '100%', height: '100%', objectPosition: 'center 21%'}} />
      </Pane>
      <Tag text="CAPTURA REAL · IPHONE 15" left={65} top={682} />
      <div style={{position: 'absolute', left: 50, top: 1155, right: 50,
        fontFamily: body, fontSize: 43, fontWeight: 700, lineHeight: 1.15}}>
        {frame < 390 ? 'Arquivo analisado antes desta reprodução.' :
          frame < 650 ? 'Em pé → descida → fundo → em pé.' :
          'Contagem local. Não avalia técnica ou segurança.'}
      </div>
      <SocialFooter text="MART PRODUCTION / Pexels · MediaPipe Pose Landmarker Full" />
    </AbsoluteFill>
  );
};

const SocialReplay = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <SocialHeader title="O +1 VEM NO FIM." />
    <Pane left={50} top={212} width={980} height={565}>
      <Video src={staticFile('phone-full.mov')} trimBefore={735} muted objectFit="cover"
        style={{width: '100%', height: '100%', objectPosition: 'center 21%'}} />
    </Pane>
    <div style={{position: 'absolute', left: 50, top: 855, right: 50,
      fontFamily: body, fontSize: 57, fontWeight: 650, lineHeight: 1.35}}>
      Pose estimada → descida<br />
      → fundo → retorno<br />
      <span style={{color: orange}}>+1 apenas ao completar</span>
    </div>
    <SocialFooter text="Replay da mesma captura; nenhum esqueleto foi gerado na edição." />
  </AbsoluteFill>
);

const SocialFourthCount = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <SocialHeader title="A QUARTA ENTRA AQUI." />
    <Pane left={50} top={228} width={980} height={575}>
      <Video src={staticFile('phone-full.mov')} trimBefore={1470} muted objectFit="cover"
        style={{width: '100%', height: '100%', objectPosition: 'center 21%'}} />
    </Pane>
    <Tag text="CAPTURA REAL · IPHONE 15" left={65} top={246} />
    <div style={{position: 'absolute', left: 50, top: 900, right: 50,
      fontFamily: body, fontSize: 58, fontWeight: 700, lineHeight: 1.2}}>
      4 ciclos observados.<br />4 contagens no aparelho.
    </div>
    <SocialFooter text="Mesmo arquivo importado; resultado limitado a este clipe." />
  </AbsoluteFill>
);

const SocialVerdict = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <SocialHeader title="UM CLIPE. QUATRO CICLOS." />
    <div style={{position: 'absolute', left: 50, top: 270, right: 50,
      fontFamily: body, fontSize: 49, color: muted}}>CONFERÊNCIA NESTE VÍDEO</div>
    <div style={{position: 'absolute', left: 50, top: 355, right: 50,
      display: 'flex', justifyContent: 'space-between'}}>
      <div><div style={{fontFamily: display, fontSize: 245, lineHeight: 0.8}}>4</div>
        <div style={{fontFamily: body, fontSize: 44}}>contagem visual</div></div>
      <div><div style={{fontFamily: display, fontSize: 245, lineHeight: 0.8,
        color: '#91A6FF'}}>4</div>
        <div style={{fontFamily: body, fontSize: 44}}>app no iPhone</div></div>
    </div>
    <div style={{position: 'absolute', left: 50, top: 720, right: 50, height: 2,
      backgroundColor: `${paper}55`}} />
    <div style={{position: 'absolute', left: 50, top: 790, right: 50,
      fontFamily: body, fontSize: 53, lineHeight: 1.22}}>
      <span style={{color: orange, fontWeight: 700}}>Experimento inicial.</span><br />
      Faltam outras condições,<br />
      50 repetições anotadas e<br />
      10 min de câmera ao vivo.
    </div>
    <SocialFooter text="Fonte: MART PRODUCTION / Pexels 8837118 · sem endosso da pessoa filmada" />
  </AbsoluteFill>
);

export const SquatCounterSocial = () => (
  <AbsoluteFill style={{backgroundColor: ink}}>
    <Sequence from={0} durationInFrames={180} name="Gancho com contagem real"><SocialHook /></Sequence>
    <Sequence from={180} durationInFrames={870} name="Fonte e iPhone"><SocialEvidence /></Sequence>
    <Sequence from={1050} durationInFrames={120} name="Quarta contagem real"><SocialFourthCount /></Sequence>
    <Sequence from={1170} durationInFrames={150} name="Replay da regra"><SocialReplay /></Sequence>
    <Sequence from={1320} durationInFrames={180} name="Limites"><SocialVerdict /></Sequence>
  </AbsoluteFill>
);

export const SquatCounterSocialCover = () => (
  <AbsoluteFill style={{backgroundColor: ink, color: paper}}>
    <SocialHeader title="O IPHONE CONTOU?" />
    <Img src={staticFile('source-frame-complete.png')} style={{position: 'absolute',
      left: 50, top: 200, width: 980, height: 420, objectFit: 'cover'}} />
    <Tag text="VÍDEO-FONTE" left={65} top={217} color={ink} />
    <Img src={staticFile('phone-frame-complete.png')} style={{position: 'absolute',
      left: 50, top: 640, width: 980, height: 510, objectFit: 'cover',
      objectPosition: 'center 21%'}} />
    <Tag text="TELA REAL DO IPHONE" left={65} top={657} />
    <div style={{position: 'absolute', left: 50, top: 1170, fontFamily: body,
      fontSize: 48, fontWeight: 700}}>4 ciclos no clipe · 4 no app</div>
    <SocialFooter text="Experimento inicial · MART PRODUCTION / Pexels" />
  </AbsoluteFill>
);
